name = "PICDataStructures"
uuid = "cb18667b-f199-4b8b-b886-9916fef47a26"
authors = ["Sebastian Micluța-Câmpeanu <m.c.sebastian95@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
